// không thay đổi file này, chỉ thay đổi cách sử dụng require trong react native

export const Paths = {
  buttons: {
    Btn1: require("./Button/Btn1.png"),
    Btn1_en: require("./Button/Btn1_en.png"),
    Btn2: require("./Button/Btn2.png"),
    Btn2_en: require("./Button/Btn2_en.png"),
    Btn3: require("./Button/Btn3.png"),
    Btn3_en: require("./Button/Btn3_en.png"),
    Btn4: require("./Button/Btn4.png"),
    Btn4_en: require("./Button/Btn4_en.png"),
    Code: require("./Button/Code.png"),
    Code_en: require("./Button/Code_en.png"),
    Ios: require("./Button/ios.png"),
    Ios_en: require("./Button/ios_en.png"),
    Android: require("./Button/Android.png"),
    Android_en: require("./Button/Android_en.png"),
    Apk: require("./Button/Apk.png"),
    Apk_en: require("./Button/Apk_en.png"),
  },
  drawer: {
    drawer: require("./Drawer/Drawer.png"),
    float_role: require("./Drawer/float_role.png"),
    Top: require("./Drawer/Top.png"),
  },
  icons: {
    HOME: require("./Icon/HOME.png"),
    FANPAGE: require("./Icon/FANPAGE.png"),
    DISCORD: require("./Icon/DISCORD.png"),
    COMMUNITY: require("./Icon/COMMUNITY.png"),
  },
  logo: {
    logo: require("./Logo/Logo_WorldofMU.png"),
  },
  text: {
    NVmoi: require("./Text/NVmoi.png"),
    NVmoi_en: require("./Text/NVmoi_en.png"),
    Text: require("./Text/Text.png"),
    Text_en: require("./Text/Text_en.png"),
    Title: require("./Text/Title.png"),
    Title_en: require("./Text/Title_en.png"),
    Title1: require("./Text/Title1.png"),
    Title1_en: require("./Text/Title1_en.png"),
    Title2: require("./Text/Title2.png"),
    Title2_en: require("./Text/Title2_en.png"),
    line: require("./Text/line.png"),
    line_mb: require("./Text/line_mb.png"),
    line_en: require("./Text/line_en.png"),
    line_mb_en: require("./Text/line_mb_en.png"),
  },
  videos: {
    Play_video: require("./video/Play_video.png"),
    KV: require("./video/KV.mp4"),
  },
  music: {
    BG_CD: require("./Music/BG_CD.png"),
    CD: require("./Music/CD.png"),
    pause: require("./Music/pause.png"),
    play: require("./Music/play.png"),
    pre_music: require("./Music/pre_music.png"),
    next_music: require("./Music/next_music.png"),
  },
  footer: {
    footer: require("./Footer/Footer.png"),
    footer_mb: require("./Footer/Footer_mb.png"),
    footer_en: require("./Footer/Footer_en.png"),
    footer_mb_en: require("./Footer/Footer_mb_en.png"),
  },
};
